name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 0.5.0
publish_to: "none"
# original homepage: https://github.com/lpongetti/flutter_map_marker_cluster
# forked homepage: https://github.com/aytunch/flutter_map_marker_cluster
homepage: https://github.com/QTree-app/flutter_map_marker_cluster

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^2.1.1
  flutter_map_marker_popup: ^3.2.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
